### ISSUE TITLE
Provide binary builds in PyPi

### ISSUE THREAD

**Issue by Lonami** [Lonami/tiny-AES-c#1]

**Comment by Lonami** [comment]
Somewhat recently I believe PyPi changed the way Linux binaries were built. Since 0.2 is out with some fixes, we should release not only the source but binaries for both Windows and Linux. For Linux, we should consider using https://github.com/pypa/manylinux.

**Comment by cher-nov** [comment]
Done in cher-nov/cryptg@1b4c91ce647999e3b1518527d97e9600e37739d7 and cher-nov/cryptg@b51fcd71302f8484e4375b20b61086fc56d54ec3.
